language: python

sudo: false

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

env:
    - DJANGO=Django==1.8.11
    - DJANGO=Django==1.9.4

matrix:
    exclude:
        - python: 3.5

matrix:
    exclude:
        - python: 3.2
          env: "DJANGO=Django==1.9.4"
        - python: 3.3
          env: "DJANGO=Django==1.9.4"


before_install:
    - pip install codecov

install:
    - pip install --pre $DJANGO django-oscar==1.2rc1
    - pip install -e .[test]

script:
    - coverage run ./runtests.py

after_success:
    - codecov
