language: python

sudo: false

python:
    - 2.7

install:
    - make install
    - pip install "django-oscar>=1.0,<1.1" "Django>=1.7,<1.8"

script:
    - coverage run ./runtests.py

after_success:
    - coveralls
